# Generated by Django 5.2.11 on 2026-02-07 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(default='system', max_length=120)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('incident_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'Sql Injection'), ('XSS', 'Xss'), ('PATH_TRAVERSAL', 'Path Traversal'), ('SUSPICIOUS_SERVICE', 'Suspicious Service'), ('DDOS_BOT', 'Ddos Bot'), ('DATA_THEFT', 'Data Theft'), ('PHISHING', 'Phishing'), ('INSIDER', 'Insider'), ('CRYPTOJACK', 'Cryptojack')], max_length=40)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=16)),
                ('query_template', models.TextField()),
                ('response_steps', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=16)),
                ('incident_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'Sql Injection'), ('XSS', 'Xss'), ('PATH_TRAVERSAL', 'Path Traversal'), ('SUSPICIOUS_SERVICE', 'Suspicious Service'), ('DDOS_BOT', 'Ddos Bot'), ('DATA_THEFT', 'Data Theft'), ('PHISHING', 'Phishing'), ('INSIDER', 'Insider'), ('CRYPTOJACK', 'Cryptojack')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('raw_event', models.JSONField(default=dict)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=16)),
                ('incident_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'Sql Injection'), ('XSS', 'Xss'), ('PATH_TRAVERSAL', 'Path Traversal'), ('SUSPICIOUS_SERVICE', 'Suspicious Service'), ('DDOS_BOT', 'Ddos Bot'), ('DATA_THEFT', 'Data Theft'), ('PHISHING', 'Phishing'), ('INSIDER', 'Insider'), ('CRYPTOJACK', 'Cryptojack')], max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('verdict', models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('DUPLICATE', 'Duplicate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('analyst_name', models.CharField(default='Unassigned', max_length=80)),
                ('analyst_group', models.CharField(default='SOC L1', max_length=80)),
                ('source_ip', models.CharField(blank=True, default='', max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('evidence', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('SIEM', 'Siem')], max_length=16)),
                ('recipients', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='soc.case')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('done', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='soc.case')),
            ],
        ),
    ]
