# Generated by Django 5.2.11 on 2026-02-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sla_critical_min', models.IntegerField(default=60)),
                ('sla_high_min', models.IntegerField(default=240)),
                ('sla_medium_min', models.IntegerField(default=480)),
                ('sla_low_min', models.IntegerField(default=1440)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telegram_handle', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(default='SOC Analyst', max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.client')),
            ],
        ),
    ]
